{
	"version": 1594179907,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/tileyellow_-sheet0.png",
		"images/tileyellow_2-sheet0.png",
		"images/tileyellow_3-sheet0.png",
		"images/enemy1-sheet0.png",
		"images/crystal-sheet0.png",
		"images/flag-sheet0.png",
		"images/batasbawah-sheet0.png",
		"images/batassamping-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite2-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/skor-sheet0.png",
		"images/menu-sheet0.png",
		"images/selamat-sheet0.png",
		"images/ulangi-sheet0.png",
		"images/cooltext-sheet0.png",
		"images/platformer-sheet0.png",
		"images/level1-sheet0.png",
		"images/level2-sheet0.png",
		"images/level3-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/spike-sheet0.png",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}